---
title: "Lake Okeechobee Water Quality Update"
output: 
  html_document:
    toc: yes
    includes:
      after_body: footer2.html
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
## Libraries
#devtools::install_github("SwampThingPaul/AnalystHelper")
library(AnalystHelper);
library(plyr)
library(reshape)

# GIS libraries 
library(rgdal)
library(rgeos)
library(raster)

wd="C:/Julian_LaCie/_Github/LakeO_WQ"

paths=paste0(wd,c("/Plots/","/export/","/Data/","/GIS"))
# Folder.Maker(paths);#One and done. Creates folders in working directory.
plot.path=paths[1]
export.path=paths[2]
data.path=paths[3]
GIS.path=paths[4]
GIS.path.gen="C:/Julian_LaCie/_GISData"

# Helper variables
nad83.pro=CRS("+init=epsg:4269")
utm17=CRS("+init=epsg:26917")

leg.fun=function(b,pal,leg.title,
                 top.val=0.8,bot.val=0.2,mid.v.val=NULL,
                 x.max=0.3,x.min=0.1,mid.val=NULL,
                 txt.offset.val=-0.01,txt.y=NULL,leg.txt=NULL,
                 txt.cex=0.75,txt.adj=0,txt.pos=4,txt.offset=0.5,
                 title.cex=0.8,title.pos=3,title.adj=0,
                 title.x=NULL,title.y=NULL,
                 leg.type=c("continuous","categorical"), ...){
  l.b=length(b)
  labs=c(paste0("< ",b[2]),paste(b[2:(l.b-2)],b[3:(l.b-1)],sep=" - "),paste(paste0(">",b[(l.b-1)])))
  n.bks=length(b)-1
  mid.v.val=if(is.null(mid.v.val)==T){bot.val+(top.val-bot.val)/2}else{mid.v.val}
  
  mid.val=if(is.null(mid.val)==T){x.min+(x.max-x.min)/2}else{mid.val}
  if(leg.type=="continuous"){
    legend_image=as.raster(matrix(rev(pal),ncol=1))
    rasterImage(legend_image,x.min,bot.val,x.max,top.val)
    txt.y=if(is.null(txt.y)==T){c(bot.val,top.val)}else(txt.y)
    leg.txt=if(is.null(leg.txt)==T){format(c(min(b),max(b)))}else(leg.txt)
    text(x=x.max, y = txt.y, labels =leg.txt,cex=txt.cex,adj=txt.adj,pos=txt.pos,offset=txt.offset, ...)
  }
  if(leg.type=="categorical"){
    bx.val= seq(bot.val,top.val,(top.val-bot.val)/n.bks)
    rect(x.min,bx.val[1:n.bks],x.max,bx.val[2:(n.bks+1)],col=rev(pal),lty=0)
    leg.txt=if(is.null(leg.txt)==T){labs}else(leg.txt)
    text(y=bx.val[2:(n.bks+1)]-c(mean(diff(bx.val[2:(n.bks+1)]))/2), x = x.max, 
         labels = rev(leg.txt),cex=txt.cex,xpd=NA,pos=txt.pos,adj=txt.adj)
  }
  
  title.x=if(is.null(title.x)==T){mid.val}else{title.x}
  title.y=if(is.null(title.y)==T){top.val}else{title.y}
  text(x=title.x,y=title.y,leg.title,adj=title.adj,cex=title.cex,pos=title.pos,xpd=NA)
}
# GIS Data ----------------------------------------------------------------

lakeO=readOGR("./GIS","LakeO")
wq.mon=readOGR("./GIS","WQmonitoring")
lakeO.lit=readOGR("./GIS","LakeOLittoral")

# WQ Sites  ----------------------------------------------------------------
sites=c(paste0("L00",1:8),"LZ40","LZ30","KISSR0.0",
        "FEBOUT","FEBIN","PALMOUT","POLE3S","MBOXSOU","MH32000","MH24000",
        "MH16000","OISLAND","TIN13700","TIN16100","RITTAE2","LZ25A","LZ25","PELBAY3",
        "PELMID","LZ2",
        paste0("TREEN",c("IN","MID","OUT")),
        paste0("TREE",c("IN","MID","OUT")),
        paste0("PLN4",c("IN","MID","OUT")),
        paste0("PLN3",c("IN","MID","OUT")),
        paste0("PLN2",c("IN","MID","OUT")),
        paste0("PLN1",c("IN","MID","OUT")),
        "RITAEAST","RITAW3","RITAWEST","LZ25",
        "LZ15","LZ42N",
        paste0("CPT",c("IN","MID","OUT")),
        paste0("KBAR",c("IN","MID","OUT")),
        paste0("3RDPT",c("IN","MID","OUT")),
        paste0("TIN",c("IN","MID","OUT")),
        paste0("IP",c("IN","MID","OUT")),
        paste0("STAKE",c("IN","MID","OUT")),
        paste0("POLES",c("IN","MID","OUT")))

site.zones=data.frame(
  SITE=c("STAKEMID", "STAKEIN", "TREEMID", "OISLAND", "3RDPTIN", "MH16000", 
         "TREEIN", "PLN3IN", "PLN3MID", "TIN13700", "STAKEOUT", "POLESMID", 
         "3RDPTOUT", "FEBIN", "PLN4MID", "TININ", "PLN1IN", "POLE3S", 
         "PELBAY3", "TINMID", "TIN16100", "MBOXSOU", "PLN2MID", "POLESOUT", 
         "PLN4OUT", "PLN2IN", "POLESIN", "KBARIN", "PLN3OUT", "IPIN", 
         "TREENOUT", "3RDPTMID", "PLN4IN", "PLN1OUT", "KBAROUT", "LZ25", 
         "TREENMID", "TREENIN", "RITAWEST", "MH32000", "LZ25A", "FEBOUT", 
         "RITAEAST", "IPMID", "PLN2OUT", "MH24000", "PLN1MID", "TREEOUT", 
         "RITTAE2", "PALMOUT", "TINOUT", "KBARMID", "KISSR0.0", "PELMID", 
         "L001", "L002", "L003", "L004", "L005", "L006", "L007", "L008", 
         "LZ40", "LZ30", "RITAW3", "LZ15"),
  zone=c("littoral", "littoral", "littoral", "littoral", "littoral", 
         "littoral", "littoral", "littoral", "littoral", "littoral", "nearshore", 
         "nearshore", "nearshore", "littoral", "nearshore", "nearshore", 
         "nearshore", "nearshore", "nearshore", "nearshore", "nearshore", 
         "littoral", "nearshore", "nearshore", "nearshore", "nearshore", 
         "nearshore", "nearshore", "nearshore", "nearshore", "nearshore", 
         "nearshore", "nearshore", "nearshore", "nearshore", "nearshore", 
         "nearshore", "nearshore", "nearshore", "littoral", "nearshore", 
         "nearshore", "nearshore", "nearshore", "nearshore", "littoral", 
         "nearshore", "nearshore", "nearshore", "nearshore", "nearshore", 
         "nearshore", "nearshore", "nearshore", "pelagic", "pelagic", 
         "pelagic", "pelagic", "pelagic", "pelagic", "pelagic", "pelagic", 
         "pelagic", "pelagic", "pelagic", "pelagic")
)

## WQ Data -------------------------------------------------
# -------------------------------------------------------------------------
dates=date.fun(c("2000-05-01",as.character(Sys.Date())))

params=data.frame(Test.Number=c(21,20,18,80,61,179,25,23,16,12),
                  param=c("TKN","NH4","NOx","TN","Chla","Chla","TP","SRP","TSS","Turb"))

dat=data.frame()
for(i in 1:length(sites)){
  tmp=DBHYDRO_WQ(dates[1],dates[2],sites[i],params$Test.Number)
  dat=rbind(tmp,dat)
  print(i)
}
dat=merge(dat,params,"Test.Number")

dat.xtab=data.frame(cast(dat,Station.ID+Date.EST~param,value="HalfMDL",mean))
dat.xtab$TN=with(dat.xtab,TN_Combine(NOx,TKN,TN))
dat.xtab$DIN=with(dat.xtab,NH4+NOx)
dat.xtab$TP=dat.xtab$TP*1000;# convert to ug/L
dat.xtab$SRP=dat.xtab$SRP*1000;# convert to ug/L
dat.xtab$WY=WY(dat.xtab$Date.EST)
dat.xtab$season=FL.Hydroseason(dat.xtab$Date.EST)
dat.xtab$month=as.numeric(format(dat.xtab$Date.EST,"%m"))
dat.xtab$CY=as.numeric(format(dat.xtab$Date.EST,"%Y"))
dat.xtab$day=as.numeric(format(dat.xtab$Date.EST,"%d"))

sites.shp=cbind(data.frame(Station.ID=subset(wq.mon,STATION%in%sites)@data$STATION),
                coordinates(subset(wq.mon,STATION%in%sites)))
colnames(sites.shp)=c("Station.ID","UTMX","UTMY")
sites.shp=SpatialPointsDataFrame(sites.shp[,c("UTMX","UTMY")],
                                 sites.shp,
                                 proj4string = utm17)

dat.xtab=merge(dat.xtab,sites.shp@data,"Station.ID",all.x=T)
dat.xtab=merge(dat.xtab,site.zones,by.x="Station.ID",by.y="SITE")

dat.xtab.month.region=ddply(dat.xtab,c("CY","month","zone"),summarise,
                            mean.TP=mean(TP,na.rm=T),sd.TP=sd(TP,na.rm=T),N.TP=N.obs(TP),SE.TP=SE(TP),
                            mean.SRP=mean(SRP,na.rm=T),sd.SRP=sd(SRP,na.rm=T),N.SRP=N.obs(SRP),SE.SRP=SE(SRP),
                            mean.TN=mean(TN,na.rm=T),sd.TN=sd(TN,na.rm=T),N.TN=N.obs(TN),SE.TN=SE(TN),
                            mean.DIN=mean(DIN,na.rm=T),sd.DIN=sd(DIN,na.rm=T),N.DIN=N.obs(DIN),SE.DIN=SE(DIN),
                            mean.Chla=mean(Chla,na.rm=T),sd.Chla=sd(Chla,na.rm=T),N.DIN=N.obs(Chla),SE.Chla=SE(Chla))
zone.vals=c("littoral","nearshore","pelagic")
fill.val=expand.grid(CY=seq(2000,as.numeric(format(dates[2],"%Y")),1),
            month=1:12,
            zone=zone.vals)
dat.xtab.month.region=merge(dat.xtab.month.region,fill.val,c("CY","month","zone"),all.y=T)
dat.xtab.month.region$date.monCY=with(dat.xtab.month.region,date.fun(paste(CY,month,01,sep="-")))

```

Updated: `r paste(format(Sys.Date(),"%B %d, %Y"))`

***
<span style="color:red;">**Disclaimer:** The data provided here should be considered preliminary and are subject to change. The data used here is from the South Florida Water Management District and available on DBHYDRO. </span>

***
## Spatial

```{r,echo=F,warning=FALSE,message=FALSE}
bks.TP=seq(0,600,100)
cols.TP=viridis::plasma(length(bks.TP)-1,alpha = 0.75)
bks.TN=seq(0,5,1)
cols.TN=viridis::magma(length(bks.TN)-1,alpha = 0.75)

t1=max(dat.xtab$Date.EST)-lubridate::duration(1,"month")
t1.dat=subset(dat.xtab,month==as.numeric(format(t1,"%m"))&CY==as.numeric(format(t1,"%Y")))
t1.dat.shp=merge(sites.shp,t1.dat,"Station.ID",all.x=T)
t1.dat.shp$TP.cols=col.vals=findInterval(t1.dat.shp$TP,bks.TP)
t1.dat.shp.TP=subset(t1.dat.shp,is.na(TP.cols)==F)
t1.dat.shp$TN.cols=col.vals=findInterval(t1.dat.shp$TN,bks.TN)
t1.dat.shp.TN=subset(t1.dat.shp,is.na(TN.cols)==F)
t1.dat.shp.TN$TN=round(t1.dat.shp.TN$TN,2)

t2=max(dat.xtab$Date.EST)
t2.dat=subset(dat.xtab,month==as.numeric(format(t2,"%m"))&CY==as.numeric(format(t2,"%Y")))
t2.dat.shp=merge(sites.shp,t2.dat,"Station.ID")
t2.dat.shp$TP.cols=col.vals=findInterval(t2.dat.shp$TP,bks.TP)
t2.dat.shp.TP=subset(t2.dat.shp,is.na(TP.cols)==F)
t2.dat.shp$TN.cols=col.vals=findInterval(t2.dat.shp$TN,bks.TN)
t2.dat.shp.TN=subset(t2.dat.shp,is.na(TN.cols)==F)
t2.dat.shp.TN$TN=round(t2.dat.shp.TN$TN,2)

```


### Total Phosphorus

```{r TPMap,echo=F,warning=FALSE,message=FALSE,fig.width=6.5,fig.height=4,fig.align='center',fig.cap="Total Phosphorus Concentrations across the lake for the last two months."}

# png(filename=paste0(plot.path,"/LOK_TP.png"),width=6.5,height=4,units="in",res=200,type="windows",bg="white")
par(family="serif",mar=c(0.1,0.1,0.1,0.1),oma=c(0.5,0.5,0.5,0.5))
layout(matrix(1:3,1,3,byrow=T),widths=c(1,0.4,1))
bbox.lims=bbox(lakeO)

plot(lakeO,border="grey",
     ylim=bbox.lims[c(2,4)],xlim=bbox.lims[c(1,3)],lwd=1)
plot(t1.dat.shp.TP,pch=21,bg=cols.TP[t1.dat.shp.TP$TP.cols],add=T,cex=1.5,lwd=0.01)
plot(lakeO.lit,add=T,col=adjustcolor("grey50",0.5),border="grey")
plot(lakeO,border="black",add=T)
text(t1.dat.shp.TP,"TP",pos=4,offset=0.5)
mtext(side=3,adj=0,line=-1.25,
      paste(min(format(t1.dat$Date.EST,"%b %d")),max(format(t1.dat$Date.EST,"%b %d, %Y")),sep=" - "))

plot(0:1,0:1,ann=F,axes=F,type="n")
leg.fun(bks.TP,cols.TP,"Total Phosphorus (\u03BCg L\u207B\u00B9)",
        leg.type = "categorical",
        txt.cex=1,title.cex = 1.25)

plot(lakeO,border="grey",
     ylim=bbox.lims[c(2,4)],xlim=bbox.lims[c(1,3)],lwd=1)
plot(t2.dat.shp.TP,pch=21,bg=cols.TP[t1.dat.shp.TP$TP.cols],add=T,cex=1.5,lwd=0.01)
plot(lakeO.lit,add=T,col=adjustcolor("grey50",0.5),border="grey")
plot(lakeO,border="black",add=T)
text(t2.dat.shp.TP,"TP",pos=4,offset=0.5)
mtext(side=3,adj=0,line=-1.25,
      paste(min(format(t2.dat$Date.EST,"%b %d")),max(format(t2.dat$Date.EST,"%b %d, %Y")),sep=" - "))
mapmisc::scaleBar(utm17,"bottomleft",bty="n",cex=0.75,seg.len=4,outer=F,col="black");

```

### Total Nitrogen
```{r TNMap,echo=F,warning=FALSE,message=FALSE,fig.width=6.5,fig.height=4,fig.align='center',fig.cap="Total Nitrogen Concentrations across the lake for the last two months."}

par(family="serif",mar=c(0.1,0.1,0.1,0.1),oma=c(0.5,0.5,0.5,0.5))
layout(matrix(1:3,1,3,byrow=T),widths=c(1,0.4,1))

bbox.lims=bbox(lakeO)

plot(lakeO,border="grey",
     ylim=bbox.lims[c(2,4)],xlim=bbox.lims[c(1,3)],lwd=1)
plot(t1.dat.shp.TN,pch=21,bg=cols.TN[t1.dat.shp.TN$TN.cols],add=T,cex=1.5,lwd=0.01)
plot(lakeO.lit,add=T,col=adjustcolor("grey50",0.5),border="grey")
plot(lakeO,border="black",add=T)
text(t1.dat.shp.TN,format(t1.dat.shp.TN$TN,nsmall=2),pos=4,offset=0.5)
mtext(side=3,adj=0,line=-1.25,
      paste(min(format(t1.dat$Date.EST,"%b %d")),max(format(t1.dat$Date.EST,"%b %d, %Y")),sep=" - "))

plot(0:1,0:1,ann=F,axes=F,type="n")
leg.fun(bks.TN,cols.TN,"Total Nitorgen (mg L\u207B\u00B9)",
        leg.type = "categorical",
        txt.cex=1,title.cex = 1.25)

plot(lakeO,border="grey",
     ylim=bbox.lims[c(2,4)],xlim=bbox.lims[c(1,3)],lwd=1)
plot(t2.dat.shp.TN,pch=21,bg=cols.TN[t1.dat.shp.TN$TN.cols],add=T,cex=1.5,lwd=0.01)
plot(lakeO.lit,add=T,col=adjustcolor("grey50",0.5),border="grey")
plot(lakeO,border="black",add=T)
text(t2.dat.shp.TN,format(t2.dat.shp.TN$TN,nsmall=2),pos=4,offset=0.5)
mtext(side=3,adj=0,line=-1.25,
      paste(min(format(t2.dat$Date.EST,"%b %d")),max(format(t2.dat$Date.EST,"%b %d, %Y")),sep=" - "))
mapmisc::scaleBar(utm17,"bottomleft",bty="n",cex=0.75,seg.len=4,outer=F,col="black");
```


## Time Series 

```{r SiteMap,echo=F,warning=FALSE,message=FALSE,fig.width=6.5,fig.height=4,fig.align='center',fig.cap="Monitoring location with littoral, nearshore and pelagic/limnetic zones identified across Lake Okeechobee. Includes active and inactive (historical) monitoring locations."}

sites.shp2=merge(sites.shp,site.zones,by.x="Station.ID",by.y="SITE")
cols=wesanderson::wes_palette("Zissou1",3,"continuous")
zone.vals.labs=c("Littoral","Nearshore","Pelagic")
par(family="serif",mar=c(0.1,0.1,0.1,0.1),oma=c(0.5,0.5,0.5,0.5))
layout(matrix(1:2,1,2,byrow=T),widths=c(1,0.4))

plot(lakeO,border="grey",
     ylim=bbox.lims[c(2,4)],xlim=bbox.lims[c(1,3)],lwd=1)
plot(lakeO.lit,add=T,col=adjustcolor("grey50",0.5),border="grey")
plot(lakeO,border="black",add=T)
plot(subset(sites.shp2,zone==zone.vals[3]),pch=21,bg=cols[3],add=T,cex=1.5,lwd=0.01)
plot(subset(sites.shp2,zone==zone.vals[2]),pch=21,bg=cols[2],add=T,cex=1.5,lwd=0.01)
plot(subset(sites.shp2,zone==zone.vals[1]),pch=21,bg=cols[1],add=T,cex=1.5,lwd=0.01)
mapmisc::scaleBar(utm17,"bottomleft",bty="n",cex=0.75,seg.len=4,outer=F,col="black");

plot(0:1,0:1,ann=F,axes=F,type="n")
legend("center",legend=zone.vals.labs,
       lty=c(0),col=c("black"),
       pch=c(21),pt.bg=cols,
       pt.cex=2,ncol=1,cex=1,bty="n",y.intersp=1,x.intersp=0.75,xpd=NA,xjust=0.5,yjust=1)

```

<br>

```{r monthlyTimeSeries,echo=FALSE,fig.width=7.5,fig.height=6,fig.align='center',fig.cap="Monthly arithmetic mean with standard error water quality parameters for littoral, nearshore and limnetic/pelagic regions of the lake."}
## Time Series Plot
edate=date.fun(paste(format(Sys.Date(),"%Y"),format(Sys.Date(),"%m"),"01",sep="-"))
sdate=date.fun(edate-lubridate::duration(18,"months"))
sdate=date.fun(paste(format(sdate,"%Y"),format(sdate,"%m"),"01",sep="-"))
cols=wesanderson::wes_palette("Zissou1",3,"continuous")
zone.vals.labs=c("Littoral","Nearshore","Pelagic")

layout(matrix(1:15,5,3,byrow=T))
par(family="serif",mar=c(1,1,0.25,0.5),oma=c(2,3,1,0.1));
xlim.val=c(sdate,edate);xmaj=seq(xlim.val[1],xlim.val[2],"6 months");xmin=seq(xlim.val[1],xlim.val[2],"1 months")

ylim.val=c(0,600);by.y=200;ymaj=seq(ylim.val[1],ylim.val[2],by.y);ymin=seq(ylim.val[1],ylim.val[2],by.y/2)
for(i in 1:3){
  plot(mean.TP~date.monCY,dat.xtab.month.region,ylim=ylim.val,xlim=xlim.val,ann=F,axes=F,type="n")  
  abline(h=ymaj,v=xmaj,lty=3,col="grey",lwd=0.5)
  with(subset(dat.xtab.month.region,zone==zone.vals[i]),pt_line_error(date.monCY,mean.TP,SE.TP,2,cols[i],1,21,cols[i],length=0.02,pt.lwd=0.01))
  #with(subset(dat.xtab.month.region,zone==zone.vals[i]),pt_line(date.monCY,mean.TP,2,cols[i],1,21,cols[i]))
  # axis_fun(1,xmaj,xmin,NA)
  # axis_fun(1,xmaj,xmin,format(xmaj,"%m-%y"),line=-0.5)
  if(i==1){
    axis_fun(2,ymaj,ymin,ymaj);
    mtext(side=2,line=2.5,"TP (\u03BCg L\u207B\u00B9)")
    }else{
      axis_fun(2,ymaj,ymin,NA)
      }
  box(lwd=1)
  mtext(side=3,zone.vals.labs[i])
}
# ylim.val=c(0,600);by.y=200;ymaj=seq(ylim.val[1],ylim.val[2],by.y);ymin=seq(ylim.val[1],ylim.val[2],by.y/2)
for(i in 1:3){
  plot(mean.TP~date.monCY,dat.xtab.month.region,ylim=ylim.val,xlim=xlim.val,ann=F,axes=F,type="n")  
  abline(h=ymaj,v=xmaj,lty=3,col="grey",lwd=0.5)
  with(subset(dat.xtab.month.region,zone==zone.vals[i]),pt_line_error(date.monCY,mean.SRP,SE.SRP,2,cols[i],1,21,cols[i],length=0.02,pt.lwd=0.01))
  #with(subset(dat.xtab.month.region,zone==zone.vals[i]),pt_line(date.monCY,mean.TP,2,cols[i],1,21,cols[i]))
  axis_fun(1,xmaj,xmin,NA)
  # axis_fun(1,xmaj,xmin,format(xmaj,"%m-%y"),line=-0.5)
  if(i==1){
    axis_fun(2,ymaj,ymin,ymaj);
    mtext(side=2,line=2.5,"SRP (\u03BCg L\u207B\u00B9)")
  }else{
    axis_fun(2,ymaj,ymin,NA)
  }
  box(lwd=1)
}

ylim.val=c(0,5);by.y=2;ymaj=seq(ylim.val[1],ylim.val[2],by.y);ymin=seq(ylim.val[1],ylim.val[2],by.y/2)
for(i in 1:3){
  plot(mean.TP~date.monCY,dat.xtab.month.region,ylim=ylim.val,xlim=xlim.val,ann=F,axes=F,type="n")  
  abline(h=ymaj,v=xmaj,lty=3,col="grey",lwd=0.5)
  with(subset(dat.xtab.month.region,zone==zone.vals[i]),pt_line_error(date.monCY,mean.TN,SE.TN,2,cols[i],1,21,cols[i],length=0.02,pt.lwd=0.01))
  #with(subset(dat.xtab.month.region,zone==zone.vals[i]),pt_line(date.monCY,mean.TP,2,cols[i],1,21,cols[i]))
  axis_fun(1,xmaj,xmin,NA)
  # axis_fun(1,xmaj,xmin,format(xmaj,"%m-%y"),line=-0.5)
  if(i==1){
    axis_fun(2,ymaj,ymin,ymaj);
    mtext(side=2,line=2.5,"TN (mg L\u207B\u00B9)")
  }else{
    axis_fun(2,ymaj,ymin,NA)
  }
  box(lwd=1)
}
ylim.val=c(0,1);by.y=0.5;ymaj=seq(ylim.val[1],ylim.val[2],by.y);ymin=seq(ylim.val[1],ylim.val[2],by.y/2)
for(i in 1:3){
  plot(mean.TP~date.monCY,dat.xtab.month.region,ylim=ylim.val,xlim=xlim.val,ann=F,axes=F,type="n")  
  abline(h=ymaj,v=xmaj,lty=3,col="grey",lwd=0.5)
  with(subset(dat.xtab.month.region,zone==zone.vals[i]),pt_line_error(date.monCY,mean.DIN,SE.DIN,2,cols[i],1,21,cols[i],length=0.02,pt.lwd=0.01))
  #with(subset(dat.xtab.month.region,zone==zone.vals[i]),pt_line(date.monCY,mean.TP,2,cols[i],1,21,cols[i]))
  axis_fun(1,xmaj,xmin,NA)
  # axis_fun(1,xmaj,xmin,format(xmaj,"%m-%y"),line=-0.5)
  if(i==1){
    axis_fun(2,ymaj,ymin,format(ymaj));
    mtext(side=2,line=2.5,"DIN (mg L\u207B\u00B9)")
  }else{
    axis_fun(2,ymaj,ymin,NA)
  }
  box(lwd=1)
}
ylim.val=c(0,300);by.y=100;ymaj=seq(ylim.val[1],ylim.val[2],by.y);ymin=seq(ylim.val[1],ylim.val[2],by.y/2)
for(i in 1:3){
  plot(mean.TP~date.monCY,dat.xtab.month.region,ylim=ylim.val,xlim=xlim.val,ann=F,axes=F,type="n")  
  abline(h=ymaj,v=xmaj,lty=3,col="grey",lwd=0.5)
  with(subset(dat.xtab.month.region,zone==zone.vals[i]),pt_line_error(date.monCY,mean.Chla,SE.Chla,2,cols[i],1,21,cols[i],length=0.02,pt.lwd=0.01))
  #with(subset(dat.xtab.month.region,zone==zone.vals[i]),pt_line(date.monCY,mean.TP,2,cols[i],1,21,cols[i]))
  # axis_fun(1,xmaj,xmin,NA)
  axis_fun(1,xmaj,xmin,format(xmaj,"%m-%y"),line=-0.5)
  if(i==1){
    axis_fun(2,ymaj,ymin,format(ymaj));
    mtext(side=2,line=2.5,"Chl-a (\u03BCg L\u207B\u00B9)")
  }else{
    axis_fun(2,ymaj,ymin,NA)
  }
  box(lwd=1)
  
}
mtext(side=1,outer=T,line=0.75,"Date (Month-Year)")


```